spring:
  application:
    name: kolayvergi-backend

  datasource:
    url: jdbc:postgresql://postgres:5432/kolayvergidb
    username: yonetici
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  sql:
    init:
      mode: always

  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    root: DEBUG

swagger:
  api:
    title: Kolay Vergi API
    description: Bu, Kolay Vergi projesi icin ozel bir API dokumantasyonudur.
    version: 1.0.0
    contact:
      name: Kolay Vergi
      email: kolayvergi@gmail.com
      url: https://kolayvergi.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 3600000
    refresh-expiration: 86400000 