version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: kolayvergi-postgres
    environment:
      POSTGRES_USER: yonetici
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kolayvergidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kolayvergi-spring-network

  springboot-app:
    build: .
    container_name: kolayvergi-springboot-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - kolayvergi-spring-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: kolayvergi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kolayvergi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - kolayvergi-spring-network

volumes:
  pgdata:

networks:
  kolayvergi-spring-network:
